version: "3.7"

services:
  influxdb:
    image: influxdb:1.7.7
    container_name: influxdb
    ports:
      - "8086:8086"
      - "8090:8090"
    env_file:
      - '.env.docker'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    restart: unless-stopped

  grafana:
    image: grafana/grafana:6.2.5
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - '.env.docker'
    links:
      - influxdb
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis-storage:/data
    restart: unless-stopped

volumes:
  influxdb-storage:
  grafana-storage:
  redis-storage:
